### ISSUE TITLE
Can't Control Apple TV  / Pi with plugin

### ISSUE THREAD

**Issue by jungopro** [jbree/homebridge-cec-accessory#15]
Hi

This is my status when Apple TV is the active source:
```bash

cec-client -d 1
log level set to 1
No device type given. Using 'recording device'
CEC Parser created - libCEC version 4.0.2
no serial port given. trying autodetect:
 path:     Raspberry Pi
 com port: RPI

opening a connection to the CEC adapter...
waiting for input
scan
requesting CEC bus information ...
CEC bus information
===================
device #0: TV
address:       0.0.0.0
active source: no
vendor:        Samsung
osd string:    TV
CEC version:   1.4
power status:  on
language:      heb


device #1: Recorder 1
address:       2.0.0.0
active source: no
vendor:        Pulse Eight
osd string:    CECTester
CEC version:   1.4
power status:  on
language:      eng


device #4: Playback 1
address:       3.0.0.0
active source: no
vendor:        Unknown
osd string:    Apple TV
CEC version:   unknown
power status:  on
language:      ???


currently active source: unknown (-1)
exit
```

this is my config.json:

```json
  "accessories": [
    {
      "accessory": "cec",
      "name": "TV",
      "type": "power",
      "address": 0
    },
    {
      "accessory": "cec",
      "name": "Pi",
      "type": "power",
      "address": 1
    },
    {
      "accessory": "cec",
      "name": "Apple TV",
      "type": "power",
      "address": 4
    }
  ],
...
```

The issues:

1. The Pi device is showing **No Response** in the Home App
2. I can't turn Apple TV on / off via the Home App

Appreciate your assistance
Omer

**Comment by jungopro** [comment]
Seems to be getting worse... I now see this in the log, and all accessories are reporting "no response":
```bash
May 08 20:48:06 raspberrypi homebridge[19885]:     at Timeout._onTimeout (/usr/lib/node_modules/homebridge-cec-accessory/node_modules/cec-promise/index.js:67:23)
May 08 20:48:06 raspberrypi homebridge[19885]:     at ontimeout (timers.js:466:11)
May 08 20:48:06 raspberrypi homebridge[19885]:     at tryOnTimeout (timers.js:304:5)
May 08 20:48:06 raspberrypi homebridge[19885]:     at Timer.listOnTimeout (timers.js:267:5)
May 08 20:48:06 raspberrypi homebridge[19885]: [2018-5-8 20:48:06] [TV] Error: No REPORT_POWER_STATUS received after 3000ms
May 08 20:48:06 raspberrypi homebridge[19885]:     at Timeout._onTimeout (/usr/lib/node_modules/homebridge-cec-accessory/node_modules/cec-promise/index.js:67:23)
May 08 20:48:06 raspberrypi homebridge[19885]:     at ontimeout (timers.js:466:11)
May 08 20:48:06 raspberrypi homebridge[19885]:     at tryOnTimeout (timers.js:304:5)
May 08 20:48:06 raspberrypi homebridge[19885]:     at Timer.listOnTimeout (timers.js:267:5)
May 08 20:48:06 raspberrypi homebridge[19885]: [2018-5-8 20:48:06] [Apple TV] Error: No REPORT_POWER_STATUS received after 3000ms
May 08 20:48:06 raspberrypi homebridge[19885]:     at Timeout._onTimeout (/usr/lib/node_modules/homebridge-cec-accessory/node_modules/cec-promise/index.js:67:23)
May 08 20:48:06 raspberrypi homebridge[19885]:     at ontimeout (timers.js:466:11)
May 08 20:48:06 raspberrypi homebridge[19885]:     at tryOnTimeout (timers.js:304:5)
May 08 20:48:06 raspberrypi homebridge[19885]:     at Timer.listOnTimeout (timers.js:267:5)
```

**Comment by jungopro** [comment]
Hello
closing this as I was able to use the Apple TV plugin instead.
