### ISSUE TITLE
Directv Power and TV Volume problem

### ISSUE THREAD

**Issue by ToddGreenfield** [jbree/homebridge-cec-accessory#2]
Hey Josh - First off, great plugin! I installed and have it working for the most part. Had to reboot after installing cec-utils to get the client to work properly. It took a couple clicks to get my TV to power on/off (works well now), however the Power for my DTV (non-primary Geni) shows a good status, but doesnt respond to commands (on/off) (I have the same issue with my DTV plugin homebridge-directv so was hoping this would solve my problems). Also, the TV volume isnt happy either. Here is a snip of my homebridge log... I will keep playing around, maybe I can incorporate some of my work with the dtv, i am not sure how you are communicating to it yet- 

[3/8/2017, 9:34:24 AM] [TV Power] getOn: 224
[3/8/2017, 9:34:24 AM] [DTV] getOn: 227
[3/8/2017, 9:34:24 AM] [TV Power] TV Power getOn: 1
[3/8/2017, 9:34:24 AM] [DTV] DTV getOn: 1
[3/8/2017, 9:34:25 AM] [TV Volume] Error: No REPORT_AUDIO_STATUS received after 1000ms
    at Timeout._onTimeout (/home/pi/.npm-global/lib/node_modules/homebridge-cec-accessory/node_modules/cec-pr                                                                                omise/index.js:63:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[3/8/2017, 9:34:37 AM] [TV Volume] Error: No REPORT_AUDIO_STATUS received after 1000ms
    at Timeout._onTimeout (/home/pi/.npm-global/lib/node_modules/homebridge-cec-accessory/node_modules/cec-pr                                                                                omise/index.js:63:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[3/8/2017, 9:36:57 AM] [DTV] getOn: 227
[3/8/2017, 9:36:58 AM] [DTV] Error: No REPORT_POWER_STATUS received after 1000ms
    at Timeout._onTimeout (/home/pi/.npm-global/lib/node_modules/homebridge-cec-accessory/node_modules/cec-promise/index.js:63:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[3/8/2017, 9:36:58 AM] [DTV] Error: No REPORT_POWER_STATUS received after 1000ms
    at Timeout._onTimeout (/home/pi/.npm-global/lib/node_modules/homebridge-cec-accessory/node_modules/cec-promise/index.js:63:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by jbree** [comment]
Todd, Thanks for the kind words! Glad you got it working...ish.

I've found that some devices require you to specifically enable "control over HDMI" or similarly named features before they'll accept commands. Might be hidden in settings, (or perhaps a firmware update: http://blog.solidsignal.com/content.php/3186-DIRECTV-rolls-out-HDMI-CEC-on-older-DVRs)

The CEC volume command is a funny thing. I could be mistaken, but the impression I get is that the volume commands are intended only to work with a receiver/audio-system device. When I tried to address volume commands to my TV it didn't work. I speculate about this in the readme, but I'm just not sure, as maybe there are some devices that support it.

If you want to look into how exactly the plugin is communicating with the devices, try running the command `cec-client` (while this plugin isn't running), and have a look at http://www.cec-o-matic.com/. You can manually address and send the cec commands and see the responses pretty easily.

Keep me posted.

**Comment by jbree** [comment]
Closing due to inactivity.
